
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Apr 21 16:48:09 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 47;
  public static final int CONST = 10;
  public static final int CASE = 44;
  public static final int LPAREN = 8;
  public static final int SEMI = 7;
  public static final int CONTINUE = 16;
  public static final int MINUS = 19;
  public static final int QSTMK = 37;
  public static final int RPAREN = 9;
  public static final int LSQR = 5;
  public static final int AND = 23;
  public static final int LT = 30;
  public static final int OR = 24;
  public static final int BOOL = 48;
  public static final int COMMA = 11;
  public static final int CLASS = 43;
  public static final int GET = 29;
  public static final int INC = 25;
  public static final int DIV = 21;
  public static final int PLUS = 18;
  public static final int IF = 49;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int EQUAL = 27;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int EQEQ = 32;
  public static final int NUMBER = 45;
  public static final int MOD = 22;
  public static final int NEQ = 33;
  public static final int IDENT = 46;
  public static final int BREAK = 35;
  public static final int VOID = 14;
  public static final int SWITCH = 41;
  public static final int COLON = 38;
  public static final int ELSE = 50;
  public static final int LBRACE = 3;
  public static final int ENUM = 42;
  public static final int READ = 34;
  public static final int RSQR = 6;
  public static final int WHILE = 17;
  public static final int LET = 31;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 39;
  public static final int PROG = 2;
  public static final int ASTK = 20;
  public static final int DEC = 26;
  public static final int GT = 28;
  public static final int DO = 36;
  public static final int PRINT = 12;
}

