
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 05 23:11:30 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 40;
  public static final int LPAREN = 8;
  public static final int SEMI = 7;
  public static final int CONTINUE = 15;
  public static final int MINUS = 18;
  public static final int QSTMK = 36;
  public static final int RPAREN = 9;
  public static final int LSQR = 5;
  public static final int AND = 22;
  public static final int LT = 29;
  public static final int OR = 23;
  public static final int BOOL = 41;
  public static final int COMMA = 10;
  public static final int GET = 28;
  public static final int INC = 24;
  public static final int DIV = 20;
  public static final int PLUS = 17;
  public static final int IF = 42;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 26;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int EQEQ = 31;
  public static final int NUMBER = 38;
  public static final int MOD = 21;
  public static final int NEQ = 32;
  public static final int IDENT = 39;
  public static final int BREAK = 34;
  public static final int VOID = 13;
  public static final int COLON = 37;
  public static final int ELSE = 43;
  public static final int LBRACE = 3;
  public static final int READ = 33;
  public static final int RSQR = 6;
  public static final int WHILE = 16;
  public static final int LET = 30;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int ASTK = 19;
  public static final int DEC = 25;
  public static final int GT = 27;
  public static final int DO = 35;
  public static final int PRINT = 11;
}

